### ISSUE TITLE
Bootstrap Theme

### ISSUE THREAD

**Issue by shaqq** [bellycard/rolodex#72]
@bellycard/apps @shayhowe 

Right now Rolodex only works with Middleman. It'd be nice to use it with Rails. Or, better yet, be backend-agnostic and allow developers to use Rolodex with any app.

**Comment by shayhowe** [comment]
Agreed! It'll take some work but we've been moving in that direction.

Thanks @shaqq!

**Comment by josephwegner** [comment]
Rolodex works with rails now. I added that like 2 weeks ago. I can walk you through on Monday. 



—

**Comment by cantyjeffrey** [comment]
Joe++

I've been using Rolodex in bellywall (rails) thanks to Joe's commit and haven't run into any issues.

**Comment by josephwegner** [comment]
To be clear, Rolodex is not 100% "backend agnostic" yet. It should work well with any ruby-based system (as long as they can use bundler, and don't, for some reason, break Sprockets). We could probably remove that dependency, and just have Rolodex be bare SASS files..  then whatever language/platform could figure out what they want to do with those files (similar to Bootstrap).

That would probably lead to child projects like `rolodex-rails` or `rolodex-middleman`, again similar to Bootstrap. I don't love that direction, but it's probably the cleanest way to be truly "backend agnostic".

All that said, @bellycard/apps has been talking a lot about moving to a grunt/gulp-based architecture. Getting Rolodex out of ruby-land would entirely remove our dependency on Ruby (aside from Middleman apps, but that's a different conversation).

**Comment by shayhowe** [comment]
Let me clarify a bit here… Rolodex is opinionated, and should be.

It should support the front-end and backend platforms Belly decides to use, and if that happens to cover other platforms by chance then great, but we shouldn't put time and effort in making it completely agnostic for the sake of it.

We took Autoprefixer out of Rolodex so that it Rolodex could work within Middleman and Rails. However, this now requires us to add Autoprefixer to each project we work on, including which browsers we're going to support. The extra work isn't ideal but the trade off is worth it for Rails support.

We shouldn't gut Rolodex of it's different dependencies so that we can kick up and play around with different platforms. If we decide to move to different platforms or build processes as a company then Rolodex will make the move, but only then.

**Comment by shaqq** [comment]
Cool! Keep us updated on the Bootstrap theme.
